services:
  backend:
    container_name: fastapi_template_backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=dev
    restart: always
    command: bash -c "alembic upgrade head && python main.py --env dev"
    ports:
      - 8001:8001
    depends_on:
      - database
    networks:
      - fastapi-template
  
  database:
    container_name: fastapi_template_database
    image: mysql:latest
    env_file:
      - .env
    ports:  
      - 3369:3306
    volumes:
      - fastapi_template_database:/var/lib/mysql
    networks:
      - fastapi-template

  phpmyadmin:
    container_name: fastapi_template_phpmyadmin
    image: phpmyadmin
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8090:80
    environment:
      PMA_HOST: fastapi_template_database
      PMA_PORT: 3306
    restart: always
    networks:
      - fastapi-template

networks:
  fastapi-template:

volumes:
  fastapi_template_database: